### ISSUE TITLE
Add comment about name of fstab copy

### ISSUE THREAD

**Issue by glteache** [malachma/azure-auto-recover#2]
A few engineers thus far were confused what happened after running the script with a fstab action. They did not fully understand the script is moving the /etc/fstab to fstab.copy, and then adding only the /boot and / lines to a new /etc/fstab file. 

I believe this will be more clear if we add to the script's output something along the lines of
"Renaming original file /etc/fstab to /etc/fstab.copy, creating new /etc/fstab file with only /boot and / partitions."

**Comment by malachma** [comment]
Thanks Glenn, I have added this to the ubuntu-Image branche
